- tutorial/mk_param_var.sh
Add shell script for parameter and variable generation from equation
> new_tutorial

- tutorial/mk_param_var.sh
fix bash script for mac add $ sign before string for mac compatibility.
> fix bash script for mac

- tutorial/last_line_paramsearch
- tutorial/mk_param_search.sh
Add bash script that gets parameter automatically from parameter list and converts to parameter list for parameter search.
> add new script for param search

- analyze.py
Add argument support for analyze.py, users can now specify the type of visualization needed for sensitivity analysis
> Add argument support

- tutorial/biomass_tutorial.md
> fix tutorial

- tutorial/biomass_tutorial.md
Add $ to signify bash command prompt
> fix command line writing

- README.ja.md
- README.md
- biomass/models/Nakakuki_Cell_2010/viz.py
Thanks for providing the useful codes.
This request includes two trivial changes:
- added a description about "experiment" option in run_simulation()
- modified viz.py to use only dark colors when number of conditions is less than 11.
This is my first pull request.
I would appreciate it if you review it, and let me know if you find any problems on this pull request.
Thank you very much!
> trivial changes on README and color settings

- biomass/analysis/initial_condition/sensitivity.py
- biomass/analysis/parameter/sensitivity.py
- biomass/analysis/reaction/sensitivity.py
- biomass/analysis/signaling_metric.py
- biomass/result.py
- tests/test_mapk_cascade.py
- Small updates in files related to sensitivity analysis
- Rename get() to to_csv() in OptimizationResults
> Update sensitivity analysis and OptimizationResults

- .gitignore
- README.ja.md
- README.md
- biomass/exec_model.py
- biomass/models/Nakakuki_Cell_2010/observable.py
- biomass/models/Nakakuki_Cell_2010/set_model.py
- biomass/models/circadian_clock/observable.py
- biomass/models/circadian_clock/set_model.py
- biomass/models/mapk_cascade/observable.py
- biomass/models/mapk_cascade/set_model.py
- biomass/models/tgfb_smad/observable.py
- biomass/models/tgfb_smad/set_model.py
- biomass/result.py
- biomass/version.py
- setup.py
- tests/test_circadian_clock.py
- tests/test_mapk_cascade.py
- tests/test_tgfb_smad.py
- From [scipy.integrate.ode](https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.ode.html) to [scipy.integrate.solve_ivp](https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.solve_ivp.html)
> Update ODE solver

- README.ja.md
- README.md
- biomass/dynamics/temporal_dynamics.py
- biomass/models/insulin_signaling/README.md
- biomass/models/insulin_signaling/__init__.py
- biomass/models/insulin_signaling/fitness.py
- biomass/models/insulin_signaling/name2idx/__init__.py
- biomass/models/insulin_signaling/name2idx/parameters.py
- biomass/models/insulin_signaling/name2idx/species.py
- biomass/models/insulin_signaling/observable.py
- biomass/models/insulin_signaling/reaction_network.py
- biomass/models/insulin_signaling/set_model.py
- biomass/models/insulin_signaling/set_search_param.py
- biomass/models/insulin_signaling/viz.py
- biomass/models/mapk_cascade/viz.py
- biomass/template/README.md
- tests/test_insulin_signaling.py
- Kubota, H. _et al._ Temporal Coding of Insulin Action through Multiplexing of the AKT Pathway. _Mol. Cell_ **46**, 820–832 (2012). https://doi.org/10.1016/j.molcel.2012.04.018
- [Kubota2012_InsulinAction_AKTpathway](https://www.ebi.ac.uk/biomodels/MODEL1204060000)
> Add the Insulin-Dependent AKT Pathway Model

- biomass/dynamics/signaling_systems.py
- biomass/dynamics/solver.py
- biomass/dynamics/temporal_dynamics.py
- setup.py
- tests/test_fos_model.py
- **biomass/dynamics/**
- Add `_preprocessing` in signaling_systems
- Fix condition when exp.data to be plotted
- Add `maximum_wait_time` to solver
- **tests**
- Use `pytest.warns` in fos_model
> Several updates

- README.md
- biomass/core.py
- biomass/dynamics/temporal_dynamics.py
- biomass/estimation/search_util.py
- biomass/result.py
- biomass/version.py
- docs/conf.py
- docs/index.rst
- docs/installation.rst
- docs/usage.rst
- setup.py
- tests/test_fos_model.py
- tests/test_mapk_cascade.py
- Create docs
- Update core functions
- Set estimated params and initials to be plotted in one figure
> Release v0.4.1

- README.md
- biomass/result.py
- docs/about.rst
- docs/index.rst
- docs/installation.rst
- docs/models.rst
- docs/usage.rst
- setup.py
- Fix result.py
- Update docs/
> Move repository to biomass-dev organization

- README.md
- biomass/analysis/initial_condition.py
- biomass/analysis/parameter.py
- biomass/analysis/reaction.py
- biomass/analysis/util.py
- biomass/core.py
- biomass/dynamics/signaling_systems.py
- biomass/dynamics/temporal_dynamics.py
- biomass/exec_model.py
- biomass/models/Nakakuki_Cell_2010/viz.py
- biomass/models/circadian_clock/README.md
- biomass/models/circadian_clock/viz.py
- biomass/models/insulin_signaling/README.md
- biomass/models/insulin_signaling/viz.py
- biomass/models/mapk_cascade/README.md
- biomass/models/mapk_cascade/viz.py
- biomass/models/nfkb_pathway/README.md
- biomass/models/nfkb_pathway/viz.py
- biomass/models/tgfb_smad/README.md
- biomass/models/tgfb_smad/viz.py
- biomass/result.py
- biomass/version.py
- docs/usage.rst
- tests/test_fos_model.py
- tests/test_mapk_cascade.py
- Template
- Add new key: `legend_kws`
- `legend_loc` becomes invalid
- Several updates to default rcParams
- Core functions
- Remove `save_format` from arguments in `run_simulation` and `run_analysis`
- To modify save_format, edit `viz.py` in the model.
- Use `x_id` to specify the index (indices) of parameter sets when running `optimize`
- `start` and `end` become invalid
- Add `create_metrics : Dict[str, Callable[[np.ndarray], Union[int, float]]], optional` to `run_analysis`
- Allowing users to crete signaling metrics for sensitivity analysis
> Release v0.5.1

- biomass/analysis/initial_condition.py
- biomass/analysis/parameter.py
- biomass/analysis/reaction.py
- biomass/analysis/util.py
- biomass/core.py
- biomass/dynamics/temporal_dynamics.py
- biomass/estimation/ga.py
- biomass/estimation/step.py
- biomass/exec_model.py
- biomass/models/Nakakuki_Cell_2010/viz.py
- biomass/models/circadian_clock/viz.py
- biomass/models/insulin_signaling/viz.py
- biomass/models/mapk_cascade/viz.py
- biomass/models/nfkb_pathway/viz.py
- biomass/models/tgfb_smad/viz.py
- biomass/plotting.py
- biomass/version.py
- docs/api/index.rst
- docs/api/visualization.rst
- docs/usage.rst
- requirements.txt
- tests/test_fos_model.py
- Template
- Update `viz.py`
Use this template for creating models with `biomass>=0.5.2`
```python
from matplotlib import pyplot as plt
from biomass.plotting import *
from .observable import Observable
class Visualization(Observable):
"""
Plotting parameters for customizing figure properties.
Attributes
----------
cm : matplotlib.colors.ListedColormap (default: `plt.cm.get_cmap('tab10')`)
Choosing colormaps for `cmap`.
single_observable_options : list of SingleObservable
Visualization options for time-course simulation (single-observable).
multiple_observables_options : MultipleObservables
Visualization options for time-course simulation (multi-observables).
sensitivity_options : SensitivityOptions
Visualization options for sensitivity analysis results.
"""
def __init__(self): …
```
> Release v0.5.2

- README.md
- biomass/core.py
- biomass/dynamics/temporal_dynamics.py
- biomass/estimation/external_optimizer.py
- biomass/plotting.py
- biomass/result.py
- docs/index.rst
This closes #71.
The error can be detected when building a model and I moved a error message from `TemproalDynamics` to `core.Model`.
> Fix error message for incorrect visualization options

- biomass/analysis/initial_condition.py
- biomass/analysis/parameter.py
- biomass/analysis/reaction.py
- biomass/core.py
> Fix sensitivity analysis visualization problem

- biomass/models/Nakakuki_Cell_2010/reaction_network.py
- biomass/models/Nakakuki_Cell_2010/set_model.py
- biomass/models/insulin_signaling/reaction_network.py
- biomass/models/insulin_signaling/set_model.py
- biomass/models/mapk_cascade/reaction_network.py
- biomass/models/mapk_cascade/set_model.py
- biomass/models/tgfb_smad/reaction_network.py
- biomass/models/tgfb_smad/set_model.py
> Move flux vector to `reaction_network.py`

- biomass/core.py
- docs/usage.rst
> docs: git clone biomass

- biomass/estimation/external_optimizer.py
- docs/usage.rst
- tests/test_fos_model.py
> Update example code for ExternalOptimizer

- biomass/result.py
- biomass/version.py
This version supports `pasmopy.optimizer`, which will be implemented in the next release.
> Release v0.6.1

- .github/workflows/build.yml
- setup.py
> Add support for Python 3.10

- .github/workflows/build.yml
- CITATION.cff
- README.md
- docs/citing.rst
- docs/index.rst
- setup.py
> Add `CITATION.cff`

- biomass/dynamics/temporal_dynamics.py
- tests/test_fos_model.py
- Shows the observable that causes the error
- Close #122
> Make error messages more user friendly

- biomass/core.py
- biomass/estimation/optimizer.py
> Add 'overwrite' option to optimizer

- biomass/core.py
- biomass/estimation/optimizer.py
- biomass/version.py
- docs/tutorial.rst
- setup.py
> Release v0.7.2

- .github/workflows/build.yml
- biomass/core.py
- biomass/dynamics/solver.py
- pyproject.toml
- requirements.txt
- setup.py
> Drop support of Python <= 3.7

- biomass/graph.py
- requirements.txt
- tests/test_graph.py
> Adding interactive plotting option. 

- biomass/graph.py
> Changed how graph is passed to pygraphvis, fixing issue #147

- biomass/graph.py
- docs/graph_visualization.rst
> Fixes documentation and changes default save directory of graph.py

- .github/workflows/build.yml
- README.md
- biomass/graph.py
- biomass/version.py
- docs/installation.rst
- requirements.txt
- setup.py
> Enable running biomass without Graphviz

- biomass/construction/reaction_rules.py
> Fix f-string in `is_phosphorylated` rule

- biomass/analysis/initial_condition.py
- biomass/analysis/parameter.py
- biomass/analysis/reaction.py
- biomass/analysis/util.py
- requirements.txt
- tests/test_fos_model.py
> Refactor code for sensitivity analysis

- biomass/construction/reaction_rules.py
This tries to address the issue #187.
Now `A --> A + B` and `A + B --> A` are equal to `A synthesizes B` and `A degrades B`, respectively.
> Redirect rules

- biomass/construction/reaction_rules.py
Added new string with _raw appendix that contains equation with species in raw form.
> Fix issue #189

- setup.py
> Set pyvis version <0.3

- biomass/core.py
- biomass/models/Nakakuki_Cell_2010/observable.py
- biomass/models/circadian_clock/observable.py
- biomass/models/g1s_transition/observable.py
- biomass/models/insulin_signaling/observable.py
- biomass/models/mapk_cascade/observable.py
- biomass/models/nfkb_pathway/observable.py
- biomass/models/pan_rtk/observable.py
- biomass/models/prolif_quies/observable.py
- biomass/models/tgfb_smad/observable.py
> Explicit return

- biomass/core.py
- biomass/models/Nakakuki_Cell_2010/observable.py
- biomass/models/circadian_clock/observable.py
- biomass/models/g1s_transition/observable.py
- biomass/models/insulin_signaling/observable.py
- biomass/models/mapk_cascade/observable.py
- biomass/models/nfkb_pathway/observable.py
- biomass/models/pan_rtk/observable.py
- biomass/models/prolif_quies/observable.py
- biomass/models/tgfb_smad/observable.py
> Explicitly return None

- biomass/estimation/optimizer.py
> Fix docstring in `Optimizer`

- README.md
- docs/index.rst
> Remove LGTM.com code quality badges

- biomass/construction/reaction_rules.py
> Fix a typo in `state_transition` rule

- biomass/construction/reaction_rules.py
- tests/test_text2model/test_error_message.py
- tests/test_text2model/test_graph.py
- tests/test_text2model/text_files/unregistered_rule.txt
- Update `state_transition` rule based on the discussion #223
- Add test for the updated rule
- Close #231 when merged
> Update `state_transition` rule in Text2Model

- biomass/core.py
- biomass/estimation/optimizer.py
- biomass/result.py
- biomass/version.py
- docs/about.rst
- docs/conf.py
- setup.py
> Release v0.11.0

- docs/about.rst
The text file should be named "michaelis_menten.txt."
> Add file name

- biomass/analysis/initial_condition.py
- biomass/analysis/parameter.py
- biomass/analysis/reaction.py
- biomass/core.py
- biomass/plotting.py
> Update arguments of `run_analysis` function

- pyproject.toml
> Remove Sphinx version constraint

- .github/workflows/build.yml
- biomass/analysis/reaction.py
- pyproject.toml
> Add support for Python 3.11 and numpy 1.24

- .readthedocs.yaml
- Fix #254 
Update .readthedocs.yaml based on the template https://docs.readthedocs.io/en/stable/config-file/v2.html
> Update .readthedocs.yaml to resolve build error

- pyproject.toml
> Don't use Sphinx version 7 or more

- pyproject.toml
> Remove Sphinx version constraints

- CITATION.cff
- README.md
- biomass/version.py
- docs/citing.rst
- docs/index.rst
As we have added a lot of functionality since I first released BioMASS, I encourage users to cite the following paper when using this software:
- Arakane, K., Imoto, H., Ormersbach, F. & Okada, M. Extending BioMASS to construct mathematical models from external knowledge. *Bioinformatics Advances*, vbae042 (2024). https://doi.org/10.1093/bioadv/vbae042
> Update citation infomation

- docs/tutorial/cfos.rst
> Add warning message
